### ISSUE TITLE
Update landing page text

### ISSUE THREAD

**Issue by gatorjuice** [actualize-portfolio/alumni_portfolio_vue#133]
The text on the landing page is now out of date

* The Rails version is 7.
* The backend is now hosted at [web-production-ad69e.up.railway.app](https://web-production-ad69e.up.railway.app/)

![Image](https://user-images.githubusercontent.com/11019755/216796315-05c96032-db88-4d98-aacb-4cddba2df11d.png)

Repository that needs the change: https://github.com/actualize-portfolio/alumni_portfolio_vue

Steps to reproduce:

* Navigate to https://alumni-portfolio.netlify.app/

Acceptance Criteria:

* update the text in the snippet to reflect the changes

**Comment by Anshtripathi079** [comment]
Can I work on this issue
